name: Martin Rotter
email: rotter.martinos@gmail.com
url: https://martinrotter.github.io

meta:
  description: Programmer, OSS fan. You can find here my personal information and some blog posts.
  author: Martin Rotter

datetime_format: '%B %e, %Y %H:%M'
exclude: ['.gitignore', 'Gemfile', 'Gemfile.lock']
timezone: Europe/Prague
permalink: pretty
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
highlighter: rouge
excerpt_separator: <!--more-->
encoding: utf-8

gems:
  - jekyll-sitemap